on: push

jobs:
    build_and_test:
        name: "Delta 2A Lidar: unit tests"
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get update && sudo apt-get install -y libudev-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: cargo test --release --all-features
